name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            print("Directory contents:")
            for f in os.listdir():
                print(f)
            import urllib.request

            from PIL import Image

            urllib.request.urlretrieve(‘https://images.app.goo.gl/7eGaJ8mQUCCzeNAg8’, “file_name”)

            img = Image.open(“file_name”)

            img.show()
